<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zmr.edu</groupId>
        <artifactId>zmr-demo</artifactId>
        <version>1.0.0</version>
    </parent>
    <modules>
        <module>zmr-system</module>
    </modules>
    <groupId>com.zmr.edu.modules</groupId>
    <artifactId>zmr-modules</artifactId>
    <packaging>pom</packaging>

    <dependencies>
        <dependency>
            <groupId>com.zmr.edu.common</groupId>
            <artifactId>zmr-common-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zmr.edu.common</groupId>
            <artifactId>zmr-common-mybatis</artifactId>
        </dependency>
    </dependencies>
</project>
